[tool.black]
line-length=120
target-version=['py39']

[tool.mypy]  
python_version = '3.9'
exclude = '(venv)'

[[tool.mypy.overrides]]
module=[
    'setuptools.*',
]
ignore_missing_imports='true'

[tool.isort]
profile = "black"
line_length = 120